logging.level.dk.jysk.taskmanager=INFO

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# ========================================
# = DATABASE CONFIGURATION (TO BE DEFINED)
# ========================================
