spring.application.name=TaskManager
server.port = 8082
spring.profiles.active=dev

# Define global logging level (INFO by default)
logging.level.root=INFO

# Customize log output pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] [%logger{36}] - %msg%n

spring.jackson.deserialization.fail-on-unknown-properties=true
